# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yRcHgT17eAT46V56RAqmrOnsQ4Vnt9B8
"""

.fit-cover {
  object-fit: cover;
}